global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: interviewhub-services
    static_configs:
      - targets:
          - auth-service:4001
          - user-service:4002
          - post-service:4003
          - file-service:4004
          - comment-service:4005
          - notification-service:4006
